name: '@dailydotdev/devcard'
description: 'GitHub Action to download the devcard from daily.dev'
author: 'Ole-Martin Bratteng'
branding:
  icon: user-check
  color: gray-dark
inputs:
  devcard_id:
    description: 'The ID of the devcard'
    required: true

  token:
    description: GitHub Token used to commit the devcard
    default: ${{ github.token }}
    required: false

  commit_branch:
    description: Branch used to commit the devcard
    default: ""
    required: false

  commit_message:
    description: Commit message
    default: Update ${filename}
    required: false

  commit_filename:
    description: Filename to save devcard to
    default: devcard.svg
    required: false

  dryrun:
    description: 'If true, no changes will be made to the repo'
    default: false
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/dailydotdev/action-devcard:2.0.2'
